/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PairHuntRouteImport } from './routes/pair-hunt'
import { Route as PatternRecallRouteImport } from './routes/pattern-recall'
import { Route as RicochetRouteImport } from './routes/ricochet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PairHuntRoute = PairHuntRouteImport.update({
  id: '/pair-hunt',
  path: '/pair-hunt',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternRecallRoute = PatternRecallRouteImport.update({
  id: '/pattern-recall',
  path: '/pattern-recall',
  getParentRoute: () => rootRouteImport,
} as any)
const RicochetRoute = RicochetRouteImport.update({
  id: '/ricochet',
  path: '/ricochet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pair-hunt': typeof PairHuntRoute
  '/pattern-recall': typeof PatternRecallRoute
  '/ricochet': typeof RicochetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pair-hunt': typeof PairHuntRoute
  '/pattern-recall': typeof PatternRecallRoute
  '/ricochet': typeof RicochetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pair-hunt': typeof PairHuntRoute
  '/pattern-recall': typeof PatternRecallRoute
  '/ricochet': typeof RicochetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pair-hunt' | '/pattern-recall' | '/ricochet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pair-hunt' | '/pattern-recall' | '/ricochet'
  id: '__root__' | '/' | '/pair-hunt' | '/pattern-recall' | '/ricochet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PairHuntRoute: typeof PairHuntRoute
  PatternRecallRoute: typeof PatternRecallRoute
  RicochetRoute: typeof RicochetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-hunt': {
      id: '/pair-hunt'
      path: '/pair-hunt'
      fullPath: '/pair-hunt'
      preLoaderRoute: typeof PairHuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern-recall': {
      id: '/pattern-recall'
      path: '/pattern-recall'
      fullPath: '/pattern-recall'
      preLoaderRoute: typeof PatternRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricochet': {
      id: '/ricochet'
      path: '/ricochet'
      fullPath: '/ricochet'
      preLoaderRoute: typeof RicochetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PairHuntRoute: PairHuntRoute,
  PatternRecallRoute: PatternRecallRoute,
  RicochetRoute: RicochetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
